package com.muscledia.muscledia_ai_service.model;

/**
 * Represents the response generated by the AI model in the AI responder service.
 * <p>
 * This record encapsulates the output of the model based on a given input question.
 * It is intended as a simple data carrier (DTO) with immutability and minimal logic.
 */
public record Answer(String answer) {
    /**
     * Factory method to safely create a new {@link Answer} instance.
     *
     * @param answer the generated response from the AI model
     * @return a validated {@link Answer} instance
     * @throws IllegalArgumentException if the answer is null or blank
     */
    public static Answer of(String answer) {
        if (answer == null || answer.isBlank()) {
            throw new IllegalArgumentException("Answer cannot be null or blank.");
        }
        return new Answer(answer);
    }
}
